<a href="https://colab.research.google.com/github/kinghim17/wind-energy/blob/main/Copy_of_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [17]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [18]:
dataset = pd.read_csv('T1.csv')
X = dataset.iloc[:, 2:5].values
y = dataset.iloc[:, 1].values


In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [19]:
print(y)

[ 380.05  453.77  306.38 ... 2201.11 2515.69 2820.47]


### Splitting the dataset into the Training set and Test set

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [21]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [24]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [25]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [26]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
1264/1264 [==============================] - 5s 3ms/step - loss: 1093219.0000
Epoch 2/100
1264/1264 [==============================] - 4s 3ms/step - loss: 169277.6250
Epoch 3/100
1264/1264 [==============================] - 3s 2ms/step - loss: 169069.1406
Epoch 4/100
1264/1264 [==============================] - 3s 2ms/step - loss: 168770.9375
Epoch 5/100
1264/1264 [==============================] - 3s 2ms/step - loss: 168661.6094
Epoch 6/100
1264/1264 [==============================] - 3s 3ms/step - loss: 167949.8906
Epoch 7/100
1264/1264 [==============================] - 4s 3ms/step - loss: 167331.8906
Epoch 8/100
1264/1264 [==============================] - 3s 2ms/step - loss: 166463.9062
Epoch 9/100
1264/1264 [==============================] - 3s 2ms/step - loss: 165804.0312
Epoch 10/100
1264/1264 [==============================] - 3s 3ms/step - loss: 165396.6562
Epoch 11/100
1264/1264 [==============================] - 4s 3ms/step - loss: 165275.0625
Epoch 12/100
1264/

### Predicting the results of the Test set

In [27]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

316/316 [==============================] - 1s 2ms/step
[[ 498.37  576.66]
 [1434.25 1619.3 ]
 [1418.32 1876.58]
 ...
 [ 600.58  667.26]
 [2997.67 3473.52]
 [2600.36 2343.06]]


### evaluation of the performance

In [28]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.907311840392626